#!/bin/sh

# For future reference, do not remove the block below, without it gnome-keyring won't work.
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
        for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
                [ -x "$f" ] && . "$f"
        done
        unset f
fi

xcompmgr &
remaps &
mpd &
dunst &
transmission-daemon &
dwmblocks &
unclutter &
setbg $HOME/Pictures/wallpapers
exec dwm
