set number relativenumber
set incsearch
set nohlsearch
set ignorecase
set smartcase
set nocompatible
set guicursor+=a:blinkon1
set encoding=utf-8
syntax on
set bg=dark
set mouse=a
set splitbelow splitright
set ruler
 
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" NetRW settings
let g:netrw_winsize = 18
let g:netrw_banner = 0
" let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_list_hide="\.pdf$, \.jpe?g$, \.png$ "
nnoremap <C-n> :Lex<CR>

" " Install vim-plug if not found
" if empty(glob('~/.vim/autoload/plug.vim'))
"   silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
"     \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" endif

" Run PlugInstall if there are missing plugins
" autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
"   \| PlugInstall --sync | source $MYVIMRC
" \| endif Install vim-plug if not found
" if empty(glob('~/.vim/autoload/plug.vim'))
"   silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
"     \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" endif

" Run PlugInstall if there are missing plugins
" autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif
call plug#begin()
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'vimwiki/vimwiki'
Plug 'vim-airline/vim-airline'
Plug 'morhetz/gruvbox'
call plug#end()

" Cntrl T to switch between tabs
	nnoremap <C-t> gt
	nnoremap <C-T> gT

" Map S to ys (surround plugin)
	nmap S ys

" Split Navigation
	map <C-j> <C-w>w
	map <C-k> <C-w>W

" Disable Auto-Comment
	autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
" Enable Auto-Complete in Command Mode
	set wildmode=longest,list,full

" Insert Lines Without Going into Insert Mode
	nmap <leader>o o<esc>k
	nmap <leader>O O<esc>j

" Move stuff around in visual mode up or down a line
	vnoremap J :m '>+1<CR>gv=gv
	vnoremap K :m '>-2<CR>gv=gv

" Shell like bindings for insert mode
imap <C-d> <C-o>de
imap <C-b> <C-o>b
imap <C-f> <C-o>w
imap <C-a> <C-o>^
imap <C-e> <C-o>$
imap <C-x> <C-o>x

" source $HOME/.config/nvim/shortcuts.vim
